# Задание на повторение материала

**1.**
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно.


In [2]:
import numpy as np

a = np.arange(12, 24, 1)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


**2.** Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [6]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [9]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

**3.** Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [11]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
a.reshape(-1, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [15]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

**4.** Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


Нет

**5.** Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [19]:
a = np.random.randn(3, 4)
print(a)

[[ 0.25331755 -1.03927145  0.53744644 -1.19120738]
 [-0.25069663  1.65585104 -1.87111106  0.96172024]
 [ 0.01214686  0.04309533 -1.60216683  0.00806099]]


In [22]:
b = a.flatten()
print(b)
#check size
a.size == b.size

[ 0.25331755 -1.03927145  0.53744644 -1.19120738 -0.25069663  1.65585104
 -1.87111106  0.96172024  0.01214686  0.04309533 -1.60216683  0.00806099]


True

**6.** Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [25]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


**7.** Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [29]:
b = np.arange(20, 1, -2)
b.reshape(1, 10)

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [30]:
np.array_equal(a, b)

True

Разница между массивами a и b отсутствует.

**8.** Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [54]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
print(a)
print('-' * 13)
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
-------------
[[1. 1.]
 [1. 1.]]


In [39]:
v = np.concatenate((a, b), axis = 0)
print(v)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [40]:
v.size

10

**9.** Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [41]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [42]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [43]:
At = A.transpose()
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [44]:
B = np.dot(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [45]:
B.size

16

In [46]:
np.linalg.det(B)

0.0

Вычислить обратную матрицу B невозможно, поскольку определитель матрицы равен 0.

**10.** Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [47]:
np.random.seed(42)

**11.** Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [50]:
c = np.arange(0, 16)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [55]:
C = c.reshape(4, 4)
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [58]:
D = C * 10 + B
print(D)

[[  5  24  43  62]
 [ 54 100 146 192]
 [103 176 249 322]
 [152 252 352 452]]


In [59]:
np.linalg.det(D)

5.18953807259442e-26

In [60]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 4.66062690e+13 -1.49229688e+13 -1.09972869e+14  7.82895692e+13]
 [ 1.63480451e+14 -3.81454387e+14  2.72467419e+14 -5.44934838e+13]
 [-4.66779710e+14  8.07677680e+14 -2.15016230e+14 -1.25881740e+14]
 [ 2.56692989e+14 -4.11300324e+14  5.25216801e+13  1.02085655e+14]]


**13.** Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [61]:
mask_pos = D_inv > 0
mask_neg = D_inv < 0

D_inv[mask_pos] = 1
D_inv[mask_neg] = 0
print(D_inv)

[[1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 1.]]


In [62]:
E = np.where(D_inv, B, C)
print(E)

[[  5   1   2  32]
 [ 14   5  86   7]
 [  8  86  10  11]
 [ 32  13 212 302]]
